### ISSUE TITLE
jle and jge wrong

### ISSUE THREAD

**Issue by lllsy12138** [xsro/masm-tasm#10]
![image](https://user-images.githubusercontent.com/50816213/99872006-8f9a7100-2c19-11eb-8ed8-69f8b3715e50.png)
jle is Jump if  less or equal，but the extension call it greater or equal.What's more,jge is supposed to be greater or equal,but the extension call it less or equal.
jle本来应该是小于等于，但是插件提示的是不小于。jge本来该是不小于，插件提示的是不大于。

**Comment by xsro** [comment]
非常感谢，插件的悬浮提示主要来自插件TASM，我翻译得不是很好，我在hoverinfo分支提供了简单的修改<https://github.com/xsro/masm-tasm/commit/df2770acd1df75aab8190c6a103524a774680b9b>, 近期我准备好好整理一下，指令信息。
