### ISSUE TITLE
open dosbox without window of CMD

### ISSUE THREAD

**Issue by Define2017** [xsro/masm-tasm#4]
# open DOSBox without window of CMD

在启动DOSBox的时候命令:dosbox.exe -noconsole就不会显示启动的命令行了.
在DOSBox.ts文件的22和40行的dosbox.exe处加上"-noconsole".
```"js"
let wincommand = 'start/min/wait "" "' + conf.path + '/dosbox/dosbox.exe" -noconsole -conf "' + conf.dosboxconfuri.fsPath + '" ';
```

**Comment by xsro** [comment]
这是可以的，但是加上`-noconsole` 会将输入输出重定向到文件中，“可能”会造成麻烦（我这样试过，并没有遇到过麻烦，但是有点担心）。
其实有些编程的时候是需要这个窗口的，比如播放音乐的编程，就可能需要这个窗口。我会在下一个版本中增加这个选项。

**Comment by xsro** [comment]
在版本`0.3.0`中，我通过增加了一个设置`masmtasm.dosbox.console`来处理这个控制台窗口，目前可以使用以下三种方式显示控制台窗口

1. 正常显示
2. 最小化显示
3. 不显示

![image](https://user-images.githubusercontent.com/64292434/94360420-a754ed80-00df-11eb-8b36-45f6e103f507.png)

感谢你的反馈
