### ISSUE TITLE
打开单个文件时，运行无响应

### ISSUE THREAD

**Issue by my-vegatable-has-exploded** [xsro/masm-tasm#6]
![image](https://user-images.githubusercontent.com/48236141/95180437-8f265200-07f4-11eb-9fa4-f3318fd9d65e.png)
点击后无反应。
vscode版本：1.49.3
windows版本：windows  19042.546

**Comment by xsro** [comment]
重启一下，还是不行吗
目前插件还不太完备，可能我也无法定位到问题所在，我会尽力尽快查找原因。

**Comment by my-vegatable-has-exploded** [comment]
> 重启一下，还是不行吗
> 
> 可以提供一下output面板里面masm-tasm输出的信息吗
> 
> 目前插件还不太完备，可能我也无法定位到问题所在，我会尽力尽快查找原因。

重启过了，没有解决。

比较奇怪的就是，output面板和terminal里面什么都没有显示，感觉没有执行，唯一有反应的就是刚装上的时候，有显示正在激活插件。

麻烦了。

**Comment by xsro** [comment]
你应该是直接打开的文件，由于目前设定的原因（只有在工作区有asm文件时才会激活插件），插件不会激活。你可以打开你那个文件所在的文件夹，应该就可以使用了，我会尝试完善激活插件的规则

非常感谢

**Comment by my-vegatable-has-exploded** [comment]
> 你应该是直接打开的文件，由于目前设定的原因（只有在工作区有asm文件时才会激活插件），插件不会激活。你可以打开你那个文件所在的文件夹，应该就可以使用了。
> 
> 我发现其实是因为我在`Activation Events`，犯了一个小错误
> 
> 非常感谢

试了一下可以了， 感谢。

用起来舒服多了。
