### ISSUE TITLE
How to include a macro?

### ISSUE THREAD

**Issue by Kariiem** [xsro/masm-tasm#9]
Hi.
Thanks a lot for this nice extension. I'm not able to include a macro file, the extension always terminates the **Run ASM code** command, with an error: can't locate file: name.inc

`include  mac.inc
.model small
.stack 64
.data
msg db "hello","$"

.code

main proc far
mov ax,@data
mov ds,ax

mov ah,9
mov dx,offset msg
int 21h
hlt
main endp
end main

`
Can't locate file: mac.inc

**Comment by xsro** [comment]
Currently this extension does not support assembly with more then one files, does not support keyword like 'include'.

I  write this extension for writing assembly in dosbox, so it may not support assembly for win32

**Comment by Kariiem** [comment]
It's an empty macro, and it is in the same directory.
`mac MACRO par

ENDM`

there are both in C:\Users\Karim\Desktop\Workspaces\Assembly Workspace, and I open the folder using vs code.

**Comment by xsro** [comment]
Hi, Currently we can use the command `dosbox here` to do this by hand.

1. open the command panel and type `dosbox here`, it will open a dosbox and the dosbox's disk E is the folder of the active file
2. in the dosbox type command you need to use


![demo](https://user-images.githubusercontent.com/64292434/99325025-5af08780-28b0-11eb-91da-85b7e4b8ff30.gif)

![pacman](https://github.com/xsro/masm-tasm/raw/main/pics/demo_pacman.gif)

**Comment by Kariiem** [comment]
Thanks a lot for your time. It worked .
